# https://taskfile.dev/
version: 3

tasks:
  build:
    cmds:
      - docker compose up --build -d
  up:
    cmds:
      - docker compose up -d
  down:
    cmds:
      - docker compose down
  down-v:
    cmds:
      - docker compose down --remove-orphans --volumes
  restart:
    cmds:
      - task: down
      - task: up
  destroy:
    cmds:
      - docker compose down --rmi all --volumes --remove-orphans

  dump-autoload:
    cmd: docker compose exec php composer dump-autoload
  bash:
    cmd: docker compose exec php bash
  docs:
    cmd: docker compose exec php php vendor/bin/openapi Modules/ -o docs/openapi.yaml
    ignore_error: true

  install:
    cmds:
      - task: prepare-env
      - task: build
      - docker compose exec php cp .env.example .env
      - docker compose exec php composer install
      - docker compose exec php chmod -R 775 storage
      - docker compose exec php chmod -R 775 bootstrap/cache
      - docker compose exec php php artisan key:generate
      - docker compose exec php php artisan storage:link
      - docker compose exec php php artisan migrate --seed
      - task: permissions

  permissions:
    cmds:
      - 'sudo chown $USER:$USER app'
  prepare-env:
    cmd: 'cp .env.example .env'

  default:
    - task: up